name: Test templates

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # run test at 11 AM UTC or 6 AM EST on the 25th of each month for monthly OL build
    - cron: 0 11 25 * *

jobs:
  java11build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - run: unset _JAVA_OPTIONS
    - name: Test simple-rest-app template
      run: |
           cd simple-rest-app
           mvn -q clean package
           mvn -q liberty:create liberty:install-feature liberty:deploy
           mvn liberty:start
           curl http://localhost:9080/api/resource/greeting
           curl http://localhost:9080/health
           mvn failsafe:integration-test liberty:stop
           mvn failsafe:verify
           docker build -t simple-rest-app:1.0-SNAPSHOT .
           docker run -d --name simple-rest-app -p 9080:9080 simple-rest-app:1.0-SNAPSHOT
           sleep 10
           docker exec simple-rest-app cat /logs/messages.log | grep product
           docker exec simple-rest-app cat /logs/messages.log | grep java
           curl http://localhost:9080/api/resource/greeting
           curl http://localhost:9080/health
           docker stop simple-rest-app
           docker rm simple-rest-app
           cd ..
    - name: Test maven template
      run: |
           cp -R simple-rest-app/src/main/java/com/demo/rest/RestResource.java maven/src/main/java/com/demo/rest/RestResource.java
           cd maven
           mvn -q clean package
           mvn -q liberty:create liberty:install-feature liberty:deploy
           mvn liberty:start
           curl http://localhost:9080/api/resource/greeting
           mvn liberty:stop
           docker build -t my-app:1.0-SNAPSHOT .
           docker run -d --name my-app -p 9080:9080 my-app:1.0-SNAPSHOT
           sleep 10
           docker exec my-app cat /logs/messages.log | grep product
           docker exec my-app cat /logs/messages.log | grep java
           curl http://localhost:9080/api/resource/greeting
           docker stop my-app
           docker rm my-app
           cd ..
    - name: Test gradle template
      run: |
           cp -R simple-rest-app/src/main/java/com/demo/rest/RestResource.java gradle/src/main/java/com/demo/rest/RestResource.java
           cd gradle
           gradle -version
           gradle tasks
           gradle clean
           gradle libertyStart
           curl http://localhost:9080/api/resource/greeting
           gradle libertyStop
           gradle libertyPackage
           docker build -t my-app:1.0-SNAPSHOT .
           docker run -d --name my-app -p 9080:9080 my-app:1.0-SNAPSHOT
           sleep 10
           docker exec my-app cat /logs/messages.log | grep product
           docker exec my-app cat /logs/messages.log | grep java
           curl http://localhost:9080/api/resource/greeting
           docker stop my-app
           docker rm my-app
           cd ..
    - name: Post tests
      if: always()
      run: |
          logsPath=$(sudo find . -name "messages.log");
          sudo cat $logsPath | sudo grep product
          sudo cat $logsPath | sudo grep java
    - name: Archive server logs if failed
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: server-logs
        path: |
              simple-rest-app/target/liberty/wlp/usr/servers/defaultServer/logs/
              maven/target/liberty/wlp/usr/servers/defaultServer/logs/
              gradle/build/wlp/usr/servers/defaultServer/logs
